# Generated by Django 4.2.5 on 2023-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Python', 'Python'), ('C#', 'C#'), ('C++', 'C++'), ('Java', 'Java'), ('JavaScript', 'JavaScripts'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Swift', 'Swift')], default='Python', max_length=155)),
            ],
        ),
    ]
